### ISSUE TITLE
ninja: error: '/configs/powerhint.json' missing

### ISSUE THREAD

**Issue by daltonfury42** [nysadev/device_xiaomi_platina#7]
It should be `$LOCAL_PATH` here:

https://github.com/nysadev/device_xiaomi_platina/blob/2e293fd8e2e5e80f798bc2dbc5c1fd331b3376ea/device.mk#L339

**Comment by nysadev** [comment]
Thanks, I did notice this on aosip-9.0. I fixed there, I will bring other branches upto date when we fully fix powerHAL.
